---
- name: Include OS family specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"

- import_tasks: sensu_grid_pre.yml
- import_tasks: sensu_grid_install.yml

- block: 
  - import_tasks: sensu_grid_search_config.yml
  - import_tasks: sensu_grid_post.yml
  tags:
    - sensu-grid-config