---
- name: Install sensu grid packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ sensu_grid_apt_packages }}"

- name: Check to see if pip is already installed.
  command: pip --version
  ignore_errors: true
  changed_when: false
  register: install_pip_is_installed

- name: Install pip if not installed
  shell: curl https://bootstrap.pypa.io/get-pip.py | python
  when: install_pip_is_installed.rc != 0

- name: Install python dependecies via pip requirements
  pip:
    requirements: "{{ sensu_grid_base_path }}/requirements.txt"



